version: '3.5'
services:
  app:
    container_name: comet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    expose:
      - '80'
    ports:
      - '8082:80'