name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@cf8514a65188af1d4f94f8c28a7a4153af1088ce
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@b67fef219a3c5542bf1d0948862a08152653b4d4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/comet
      
      - name: Build and push Docker image
        uses: docker/build-push-action@4e4ee680f69700760d5620a94c020aef883043aa
        with:
          context: .
          file: ./docker-compose.yml
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
